### ISSUE TITLE
Feature request: Override Apple brightness keys

### ISSUE THREAD

**Issue by ivanhtp** [alin23/Lunar#23]
Hi there!

First things first, congratulations on the app. It's amazing and works really well with my monitor.

I currently have a mac mini with an external (LG Ultra HD) monitor. I only use this monitor and since it's not an official one from apple, my brightness keys (f1, f2) have no function at all. I'm using the Lunar shortcuts (ctrl+f1, ctrl+f2) but it would be awesome if I could override the apple function keys to use the original ones (without need to press "fn" and "control" anymore. It would be ultra friendly.

Thanks!

**Comment by alin23** [comment]
Hey, thanks for the message!

I couldn't find a way to override the Mac function keys, I think this is restricted by the system. There is [Karabiner Elements](https://pqrs.org/osx/karabiner/document.html) that can do that but it uses a kernel extension to achieve that. I find that too intrusive to include in Lunar (also I have no idea how to write kernel extensions and I would have to allocate a lot of time just to learn this)

Maybe you could use Karabiner to remap the brightness keys to Lunar hotkeys ^_^

**Comment by ivanhtp** [comment]
I'll give it a try! 
I tried https://github.com/the0neyouseek/MonitorControl, it seems to handle the key override well but the implementation itself is a little bit sluggish.

Thanks!

**Comment by alin23** [comment]
Huh, it also has volume control. Thanks for letting me know about MonitorControl, I'll try to steal a few things from there.

**Comment by CedFlanders** [comment]
I was going to ask about the same feature, after finding this thread I guess there's no need to start a new one :). I'm currently also using monitorcontrol on a Mac mini. But like you say it doesn't work as well as Lunar App. 
Lunar App is already amazing and it would be even more perfect if I could use the default keys (and see the on screen overlay) like in monitorcontrol.

**Comment by alin23** [comment]
I'll try to find some time for this, I didn't know it would be such a wanted feature 😅

**Comment by Mic238** [comment]
I achieve this by mapping the original brightness control to f16/f17 with karabinder and update the keyboard shortcut according, which is just perfect except for no long press recognition (which I've opened an new issue for) or popup like the volume control. I think it's good enough as a long term  solution but obviously a native built in would be more appreciated

**Comment by alin23** [comment]
Thanks for sharing the workaround! Yes, I plan to implement this in Lunar as soon as possible.

**Comment by jalendport** [comment]
Ooo thanks for the workaround @Mic238... that should work perfectly for my needs. I can setup the remap (F1/F2 => F16/F17) for only my external keyboard, so I'm not breaking the default brightness controls if I'm working on my Macbook itself. I'm also using what would be the keyboard brightness controls on an internal Mac keyboard to adjust the contrast (F5/F6 => F18/F19).

It would be nice if the increments could be larger; currently takes way too many taps to go from like 25% to 75% - I would love to see something more akin to the number of increments in the default macOS brightness switcher (jumping by like 8% instead of 3%).

**Comment by alin23** [comment]
Hi @jalendport @ivanhtp @Mic238  @CedFlanders !
Would you like to help me beta test a Lunar version with support for changing volume, media keys and displaying native OSD? I would especially like to know how it works on multiple external monitors.

You can find the beta version here: https://transfer.sh/fv5J1/Lunar-2.9.11.dmg

What I'd like to know:
1. Check if media keys work. You can check that by pressing brightness and volume keys while you have the cursor on the external monitor and seeing if the brightness/volume actually changes.
![image](https://user-images.githubusercontent.com/3819725/75254418-a1f99280-57e0-11ea-8ff8-765ef0590f15.png)
![image](https://user-images.githubusercontent.com/3819725/75254440-aaea6400-57e0-11ea-8769-e2b8014a5c4c.png)

2. Check if the volume changes with the volume hotkeys when you have the monitor audio output selected. The default volume hotkeys are CTRL+F11/F12 or the volume media keys if point 1 works.
![image](https://user-images.githubusercontent.com/3819725/75254276-6b237c80-57e0-11ea-98e1-01a27ad557ff.png)

3. Check if you get the native On-Screen Display showing when changing brightness/contrast/volume with the hotkeys.
<img width="208" alt="Screenshot 2020-02-25 at 15 04 27" src="https://user-images.githubusercontent.com/3819725/75254160-34e5fd00-57e0-11ea-884a-abd5948547ff.png">

**Comment by ivanhtp** [comment]
Sure! I'm on a travel right now but I'll try it as soon as I can.

Great feature.

**Comment by Mic238** [comment]
Alright I ran the beta and I think it's a great starting point with some fixings required.

Test Machine:
Mac mini 2014, Catalina 10.15.3, with single external monitor only Samsung SE24E390HL

Native Display with Media Key:
N/A, Mac mini doesn't have a built in display.

External Display with Media Key:
The enable and disable of "use media hotkey as shortcut" doesn't take effect until restart Lunar.
It updates the brightness and contrast alright but OSD popup is not shown up

External Display with Shortcut:
Work as usual, The OSD popup shows up beautifully for both brightness and contrast

External Display Volume:
Volume down crash the app completely
Volume up has OSD shows up but it doesn't actually change the volume of the monitor (It could be a monitor thing, need to be confirmed)

Nice Work!

**Comment by Mic238** [comment]
Second Monitor with Sidebar/iPad:
The main monitor change brightness even when the cursor is on iPad, OSD shows on both screens. (Probably because iPad doesn't allow brightness change?)

**Comment by alin23** [comment]
Thanks @Mic238 for the detailed report! It seems I forgot to show the OSD on media keys press. 
I fixed that and the volume change crash.

I can't do much about the iPad Sidecar. There's no API to change brightness/contrast/volume of a Sidecar device and DDC doesn't work without a cable. But the media keys should not change the main monitor brightness now if the cursor is on the iPad display. 

Also now Lunar should detect that a monitor doesn't respond to DDC messages and show that in the Quick Actions popover. You'll see that for the iPad after a few failed brightness/contrast changes.
![image](https://user-images.githubusercontent.com/3819725/75365056-f1ad8c00-58bc-11ea-8138-6aab28f4d791.png)

The fixed version is here: https://transfer.sh/UUNgO/Lunar-2.9.11-2.dmg

**Comment by Mic238** [comment]
> Thanks @Mic238 for the detailed report! It seems I forgot to show the OSD on media keys press.
> I fixed that and the volume change crash.
> 
> I can't do much about the iPad Sidecar. There's no API to change brightness/contrast/volume of a Sidecar device and DDC doesn't work without a cable. But the media keys should not change the main monitor brightness now if the cursor is on the iPad display.
> 
> Also now Lunar should detect that a monitor doesn't respond to DDC messages and show that in the Quick Actions popover. You'll see that for the iPad after a few failed brightness/contrast changes.
> ![image](https://user-images.githubusercontent.com/3819725/75365056-f1ad8c00-58bc-11ea-8138-6aab28f4d791.png)
> 
> The fixed version is here: https://transfer.sh/UUNgO/Lunar-2.9.11-2.dmg

Cannot download the fixed version, file not found

**Comment by alin23** [comment]
That's weird, I can still download it. Try this one on Firefox send: https://send.firefox.com/download/b212444c1299726a/#gP5BgbNg-7YysLGPv8oVvg

I agree, we can move on to 3.0 with this.

**Comment by Mic238** [comment]
> Also now Lunar should detect that a monitor doesn't respond to DDC messages and show that in the Quick Actions popover. You'll see that for the iPad after a few failed brightness/contrast changes.
No luck, the brightness only changes the main display with shortcut, no matter where the cursor is. And when I change on lunar window, it doesn't show no DDC support.
(I suppose DDC just got ignored for sidecar? Not a big deal though)

Volume Mute OSD is a little bit different from system one (volume bar is all grey on mute), and I can't unmute by pressing mute media key again (shortcut is fine), need fixing.

> The enable and disable of "use media hotkey as shortcut" doesn't take effect until restart Lunar.
Await fixing.
In addition, I think it's better to separate "use media key as shortcut" menu items for brightness/contrast and volume, currently use media key replace both brightness and volume, iMac users would not like this. Also need a step control for volume as well.

Given a long list of drop down menu items, probably move some of them to a separate page on lunar window? Most of them are not touched after initial setup anyway.

**Comment by alin23** [comment]
Fixed version here: https://send.firefox.com/download/f1bd0610c31880b7/#To5o3AeQ0Ao4s4iE_s-tLw

> No luck, the brightness only changes the main display with shortcut, no matter where the cursor is. And when I change on lunar window, it doesn't show no DDC support.
> (I suppose DDC just got ignored for sidecar? Not a big deal though)

That's expected. DDC is an I2C protocol, which only works by passing high frequency electrical pulses through wires. Sidecar uses Airplay which being wireless doesn't support DDC. If you try to change the brightness of the iPad through Lunar, after 20 failed DDC writes Lunar will show that **Non-responsive DDC** message. There's no way to detect that the monitor is an iPad or any other wireless display.

> Volume Mute OSD is a little bit different from system one (volume bar is all grey on mute), and I can't unmute by pressing mute media key again (shortcut is fine), need fixing.

I'm using the system OSD framework, I don't see how it could look different. In this version I tried to fix this by linking the OSD framework from the user system instead of embedding it. Please let me know if the new version still has this problem.

The mute/unmute problem should also be fixed.

> > The enable and disable of "use media hotkey as shortcut" doesn't take effect until restart Lunar.

Fixed, thanks for catching this.

> In addition, I think it's better to separate "use media key as shortcut" menu items for brightness/contrast and volume, currently use media key replace both brightness and volume, iMac users would not like this. Also need a step control for volume as well.

Brightness and volume keys don't need separation because the volume keys are only overridden if the audio output is external and doesn't already have native volume control and the brightness keys can change both the built-in brightness and the external brightness based on where the cursor is.

I added a volume step setting on the configuration page:
![image](https://user-images.githubusercontent.com/3819725/75454332-8ecbfb80-5975-11ea-90b8-cf3768effa90.png)

> Given a long list of drop down menu items, probably move some of them to a separate page on lunar window? Most of them are not touched after initial setup anyway.

I'll keep the settings in the menu for now until I find a good solution for them. Those are important settings that help with troubleshooting and I wouldn't want to hide them in another obscure page. I'll think about a better way to organise them in the near future.

**Comment by Mic238** [comment]
Mostly Minor Problem now, I think it's nearly the time to move out of beta.

> If you try to change the brightness of the iPad through Lunar, after 20 failed DDC writes Lunar will show that Non-responsive DDC message. There's no way to detect that the monitor is an iPad or any other wireless display.

I can see this as expected that iPad doesn't take DDC, but the unexpected part was that the main display would change brightness when the cursor is on iPad. The OSD has a "not allowed" mark for volume and should be for brightness/contrast as well, maybe you can take use of this? 

![image](https://user-images.githubusercontent.com/20364101/75495285-49114080-5a12-11ea-8fc7-e4a61a307555.png)

> I'm using the system OSD framework, I don't see how it could look different. In this version I tried to fix this by linking the OSD framework from the user system instead of embedding it. Please let me know if the new version still has this problem.

This problem still exists and now creates a new issue that adjusting volume wouldn't change mute to unmute. Also lunar OSD stays longer on screen than the native one.

> I added a volume step setting on the configuration page
Each step in OSD is 6.67 (100 x 1/16), maybe allow this value as well so each press is a full step? The OSD looks a bit weird after pressing like 10+ times from 0 to 60
(My step setting is 6, maybe it's just my OCD)

**Comment by alin23** [comment]
Lunar 3.0 will be released in the following hours. Thanks a lot for all the help!

> I can see this as expected that iPad doesn't take DDC, but the unexpected part was that the main display would change brightness when the cursor is on iPad. The OSD has a "not allowed" mark for volume and should be for brightness/contrast as well, maybe you can take use of this?
> 
> ![image](https://user-images.githubusercontent.com/20364101/75495285-49114080-5a12-11ea-8fc7-e4a61a307555.png)

This is shown by the system, not by Lunar. I don't have access to the private API that's showing the not allowed mark. The only thing I can show is a locked icon:
<img width="204" alt="Screenshot 2020-02-28 at 11 28 50 (2)" src="https://user-images.githubusercontent.com/3819725/75541128-a8288280-5a1d-11ea-8af5-a3d161ff543a.png">


The problem about the main display happens because sometimes the system wrongly reports the cursor being on the builtin display. I can't do anything about that, macOS is a nice platform to develop for but it is far from perfect.
 
> This problem still exists and now creates a new issue that adjusting volume wouldn't change mute to unmute. Also lunar OSD stays longer on screen than the native one.

I added the `unmute if changing volume` logic and lowered the fade down of the OSD from `2000ms` to `1500ms`

> Each step in OSD is 6.67 (edit: should be 6.25, 100 x 1/16), maybe allow this value as well so each press is a full step? The OSD looks a bit weird after pressing like 10+ times from 0 to 60
> (My step setting is 6, maybe it's just my OCD)

The OSD receives the following params for this:
```swift
            filledChiclets: value,
            totalChiclets: 100,
```
Those values are integers so I can't send 6.25 or any other float value. The problem here is that the range is 0-100 which is not divisible by 16, whereas the builtin volume range is something like 0-128. We'll have to live with incomplete chiclets.

**Comment by Lonli-Lokli** [comment]
@alin23 I have the latest Lunar installed and not able to change external monitor brightness with default settings.

Also I've erased CtrlF1 shortcut and now I am not able to set it again, it just do not allow it.

**Comment by Mic238** [comment]
> @alin23 I have the latest Lunar installed and not able to change external monitor brightness with default settings.
> 
> Also I've erased CtrlF1 shortcut and now I am not able to set it again, it just do not allow it.

Can you post out your machine and connection method? "not able to change" means nothing to diagnostic the issue

For shortcut, try fn+ctrl+f1, most likely you have a default media key setting (play/pause/volume control/etc) instead of using them as function key (f1/f2/etc), so fn+f1 = actual f1. Alternatively, enable the media control override on lunar menu located in advance.
![image](https://user-images.githubusercontent.com/20364101/96095618-92b78880-0f1a-11eb-8f15-220f3db933fe.png)

**Comment by Lonli-Lokli** [comment]
I have Macbook Pro 2018 13, Macos 10.15.7
My external monitor is connected via Thunderbolt3 

Symptoms -
When I press F1 or F2 on mac screen - it updates brighness as required.
When I press F1 or F2 on external screen - macos popup with sun image appears but it does not react to any future presses and actually do not change brightness.

**Comment by alin23** [comment]
@Mic238 thanks for stepping in!

@Lonli-Lokli 
The volume keys should work in all modes (Sync, Location and Manual). Just make sure that the monitor audio device is selected as the output:

![image](https://user-images.githubusercontent.com/3819725/96131094-71966e00-0f01-11eb-95f8-c4f23c248047.png)

**Comment by eduardomart** [comment]
I migrated my Mac to a new SSD, and now Lunar won't use the F1/F2 keys when connected to my external monitor. Before the migration they worked normally, as they work with my Macbook's built-in keyboard/screen.

I don't know what happened, but now I have to use FN+F1 or FN+F2 for screen adjustments to work. I would really like to have it back so that I don't have to use modifier keys, I tried changing it in settings, but if I just hit F1 while 'editing' the key shortcuts, absolutely nothing happens.

**Comment by Mic238** [comment]
> I migrated my Mac to a new SSD, and now Lunar won't use the F1/F2 keys when connected to my external monitor and keyboard. Before the migration they worked normally, as they work with my Macbook's built-in keyboard/screen.
> 
> I don't know what happened, but now I have to use FN+F1 or FN+F2 for screen adjustments to work. I would really like to have it back so that I don't have to use modifier keys, I tried changing it in settings, but if I just hit F1 while 'editing' the key shortcuts, absolutely nothing happens.

The most likely is that the system uses the f key as media key, Go to system pref - keyboard and tick "use f1, f2, etc as functional key" should solve the issue

**Comment by eduardomart** [comment]
@Mic238 thanks for the reply, but that doesn't really solve the problem, the sys prefs thing you mentioned just creates its own set of problems, not being able to use the rest of the keys without now having to press fn for them to do what they normally do.

I wonder how it is that I had it working as it all should before I switched hard drives and now it's all effed up. I really don't want to use yet another app just to solve this one thing.  Really frustrating.

**Comment by alin23** [comment]
@eduardomart it's possible that the Input Monitoring permissions have been revoked because of switching the SSD.

Make sure Lunar is in the Input Monitoring list in Security & Privacy (if it is, check and uncheck it for the permission to re-apply after).
Lunar needs these permissions in order to listen globally to the brightness and volume keys.

![40302A88-4F2E-455E-881D-6836F23C78E6](https://user-images.githubusercontent.com/3819725/110294623-bfb72580-7ff8-11eb-8175-b9c5e21049e0.png)

**Comment by eduardomart** [comment]
Thanks for the pointers @alin23, Lunar was not in the input monitoring section, I added it, and still nothing. Also tried unchecking/checking again and still no dice.

I think the problem is that when I try to setup shortcuts in Lunar, with the keys I want (Brightness Up/Down - without fn keys) Lunar doesn't recognize the keys, nothing happens, I can only use shortcuts with modifier keys.

**Comment by alin23** [comment]
> Edit:
I actually went to the Accessibility section in Security & Privacy and unchecked/checked Lunar again and that actually seems to have done the trick!

Great to hear!

> I think the problem is that when I try to setup shortcuts in Lunar, with the keys I want (Brightness Up/Down - without fn keys) Lunar doesn't recognize the keys, nothing happens, I can only use shortcuts with modifier keys.

Brightness keys are special keys (totally different from F1/F2) and can't be recorded as hotkeys. That's why there's a different setting for enabling Lunar to intercept media keys events.

**Comment by eduardomart** [comment]
So.... Keys are not working again, have no idea why, nothing has changed, I tried the same trick as before, no dice.

**Comment by Pascauli** [comment]
@eduardomart and all others having the issue with the standard Function Keys not working after some kind of change:

Try looking for other Security&Privacy Options in the System Preferences I just enabled it in all categories it was in. So not only some input method or Accessibility, but all categories – since I am very lazy and also trust Lunar developers.

It worked fine. I also had a hard time realising it might be a system setting. Thanks to the developer and all the solutions above, they helped me getting it back to normal.
![Screenshot 2021-06-07 at 09 31 30](https://user-images.githubusercontent.com/38542387/120976991-27ede280-c773-11eb-9373-797c29effc37.png)

**Comment by alin23** [comment]
@Pascauli thanks for the details on this! I've also written an FAQ about this here for when macOS misbehaves and cripples permissions completely: https://lunar.fyi/faq#always-asks-for-permissions
