### ISSUE TITLE
Lunar Bug(s) - Lunar UI doesn't persist monitor's name & tray scrolling sensitivity too low

### ISSUE THREAD

**Issue by jakubbania** [alin23/Lunar#352]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    *Macbook Pro 2017*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *DELL U2412M*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *not sure, hdmi to hub, hub to mac device*

- Using an USB Docking Station or Hub:
    *yes*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

no - the core functionalities are working fine

# Issue description:

1. Lunar doesnt persist monitors name after changing it in preferences panel.
- Go into preferences
- Change monitor's name
- Use arrow key to navigate to a different monitor
- Use arrow key to go back to previous monitor
- The name didnt persist and has been set to default monitor model's name

2. Lunar tray hover modal has low sensitivity when scrolling to change values, using external usb mouse with scrolling wheel.
- Hover over Lunar tray icon
- Wait for modal to show
- Hover over any brightness / contrast value
- Scroll over the value - i need to scroll really hard with my mouse scrolling wheel to change the value by 1. 

**Note from my side:**
Using macbook's trackpad the scrolling sensitivity is OK! 
I had this issue in other browser application I was developing, the thing is that macos has some shady logic going on about scrolling event delta value, which is quite high when using trackpad / magic mouse / magic trackpad but using external mouse its noticeably lower, which results in such difference.

**Comment by alin23** [comment]
Hi! I'm aware of the name persistence issue and it's already fixed in master. I'm preparing for a new release soon. 

About the sensitivity too low, you can hold Option while scrolling for higher sensitivity.

**Comment by jakubbania** [comment]
ad.1 Thank you 👍 
ad.2 Its still not sensitive enough while holding option, and I would say it barely changes anything as it still requires a considerable amount of effort to reduce the value as little as from 100 to 75.
This scrolling worked much better in previous versions of Lunar

btw. Great app! ;)

**Comment by alin23** [comment]
That's odd. Holding option actually uses a much higher sensitivity than the default on Lunar 3. And most people actually complain about scrolling being too sensitive, no one complained about it being too slow. 

I don't know what else I could do about this.

**Comment by alin23** [comment]
Maybe I can add an "as fast as possible" sensitivity when holding both Command and Option.

**Comment by jakubbania** [comment]
https://user-images.githubusercontent.com/51878282/121695816-b643ca80-cacb-11eb-9f92-7f021bb48e24.mov

^ i am holding option and trust me, I'm scrolling like a mad man; you can see the result
Its not 'necessary' for me, because most of the time i use set values, but when I f.eg. want to change settings only for one monitor, this is the case where I mostly use it and I havent found yet a better way to set that

**Comment by jakubbania** [comment]
I will be more than happy to see (if) improvements in this scrolling in the next version. Good luck! Issue can be closed.

**Comment by alin23** [comment]
This should be fixed in v4.1.0. Let me know if it still happens and I'll reopen this.
