### ISSUE TITLE
Settings forced change when desktop is switched

### ISSUE THREAD

**Issue by 1natsu172** [alin23/Lunar#7]
Thanks for great app. This is a bug report.

---

Lunar settings are unintentionally changed when switching desktop on Mac.

For example, the brightness is set to 0 then switch other desktop… the screen gets brighter.
Although the screen gets brighter, the setting value on the UI is not changed.

_The "desktop" I am talking about is the desktop of MacOS standard functions in mission control._

**Comment by alin23** [comment]
Hello! Thanks for the feedback!

Unfortunately I can't reproduce this and I'm not seeing anything in the logs. I'm working on a debug system that would make bugs like these easier to debug in the future. I'll keep this issue as reference for now.

If you'll have time, I'd be glad if you would help me debug this when the new update is ready ^_^

**Comment by 1natsu172** [comment]
@alin23 Thanks for reply!

> Unfortunately I can't reproduce this

It might be a problem specific to the environment ...?
I forgot to write versions. Lunar is v2.1.2. The MacOS is Mojave. Using external display is BDM4350UC/11 of Philips.

Since I just updated to Mojave, this bug may be affected by other applications.
I will investigate even a bit more.

> If you'll have time, I'd be glad if you would help me debug this when the new update is ready ^_^

Yes, welcome!

**Comment by alin23** [comment]
Please reopen the issue if this happens again. I made some changes that should fix this but as I couldn't reproduce the bug in the first place, I had no way to validate them.

**Comment by 1natsu172** [comment]
Thanks some fix & update, but the problem was not solved. This problem continues to arise...

This is probably an environment-specific problem, so refrain from reopening Issue.
